# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/powerhouse_db
spring.datasource.username=postgres
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# App
server.port=8082
spring.application.name=fitness-api

# JWT
app.jwt.secret=powerhouseSecretKey2024powerhouseSecretKey2024powerhouseKey
app.jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Disable open-in-view warning
spring.jpa.open-in-view=false